# Generated by Django 2.2.4 on 2020-06-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_yelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='approval',
            field=models.IntegerField(default=0),
        ),
    ]
